@base_url = http://127.0.0.1:8000/api
@access_token =
@refresh_token =
@plan_id =
@session_id =
@session_exercise_id =
@set_id =

### 1) Register
POST {{base_url}}/auth/register/
Content-Type: application/json

{
  "username": "alex",
  "email": "alex@mail.com",
  "password": "123456"
}

### 2) Login (save tokens)
POST {{base_url}}/auth/login/
Content-Type: application/json

{
  "email": "alex@mail.com",
  "password": "123456"
}

> {%
client.global.set("access_token", response.body.access);
client.global.set("refresh_token", response.body.refresh);
%}

### 3) Me (check token works)
GET {{base_url}}/auth/me/
Authorization: Bearer {{access_token}}

### 4) Refresh access (if access expired)
POST {{base_url}}/auth/refresh/
Content-Type: application/json

{
  "refresh": "{{refresh_token}}"
}

> {%
client.global.set("access_token", response.body.access);
%}

### 5) Public catalog: categories
GET {{base_url}}/categories/

### 6) Public catalog: exercises
GET {{base_url}}/exercises/

### 7) Create workout plan (authorized) + save plan_id
POST {{base_url}}/plans/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "My plan A",
  "description": "Simple plan"
}

> {%
client.global.set("plan_id", response.body.id);
%}

### 8) List my plans
GET {{base_url}}/plans/
Authorization: Bearer {{access_token}}

### 9) Create session from plan (authorized) + save session_id
POST {{base_url}}/plans/{{plan_id}}/create_session/
Authorization: Bearer {{access_token}}

> {%
client.global.set("session_id", response.body.id);
%}

### 10) List my sessions
GET {{base_url}}/sessions/
Authorization: Bearer {{access_token}}

### 11) Get session details (see session_exercise_id inside response)
GET {{base_url}}/sessions/{{session_id}}/
Authorization: Bearer {{access_token}}

### 12) Add set to existing session_exercise (authorized)
POST {{base_url}}/session-sets/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "session_exercise": {{session_exercise_id}},
  "reps": 10,
  "weight": 50
}

### 13) List sets (authorized)
GET {{base_url}}/session-sets/
Authorization: Bearer {{access_token}}
