# Generated by Django 5.2.10 on 2026-01-14 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=45)),
                ('signup_date', models.DateTimeField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('category', models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.categories')),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('session_exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=45, null=True)),
                ('exercise', models.ForeignKey(db_column='exercise_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.exercises')),
            ],
            options={
                'db_table': 'sessionexercise',
            },
        ),
        migrations.CreateModel(
            name='SessionExerciseSets',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('set_number', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('session_exercise', models.ForeignKey(db_column='session_exercise_id', on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='fitness.sessionexercise')),
            ],
            options={
                'db_table': 'sessionexercisesets',
            },
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_type', models.CharField(max_length=45)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='fitness.users')),
            ],
            options={
                'db_table': 'goals',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='fitness.users')),
            ],
            options={
                'db_table': 'workoutplan',
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('duration_min', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=45, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='fitness.users')),
            ],
            options={
                'db_table': 'workoutsession',
            },
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='session',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='fitness.workoutsession'),
        ),
        migrations.CreateModel(
            name='ExerciseEquipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.equipment')),
                ('exercise', models.ForeignKey(db_column='exercise_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.exercises')),
            ],
            options={
                'db_table': 'exerciseequipment',
                'unique_together': {('exercise', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='PlanExercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(blank=True, max_length=45, null=True)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(db_column='exercise_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.exercises')),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.workoutplan')),
            ],
            options={
                'db_table': 'planexercise',
                'unique_together': {('plan', 'exercise')},
            },
        ),
    ]
