# Generated by Django 5.2.10 on 2026-03-03 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('signup_date', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_current', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('DifficultyLevel', models.CharField(max_length=30)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.categories')),
                ('User_id', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.users')),
            ],
            options={
                'db_table': 'Exercises',
            },
        ),
        migrations.CreateModel(
            name='ExerciseEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.equipment')),
                ('exercise_id', models.ForeignKey(db_column='exercise_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.exercises')),
            ],
            options={
                'db_table': 'ExerciseEquipment',
            },
        ),
        migrations.CreateModel(
            name='ExercisesGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exercises_exercise_id', models.ForeignKey(db_column='Exercises_exercise_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.exercises')),
                ('Goals_goal_id', models.ForeignKey(db_column='Goals_goal_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.goals')),
            ],
            options={
                'db_table': 'ExercisesGoals',
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('notes', models.CharField(max_length=255)),
                ('session_exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_id', models.ForeignKey(db_column='exercise_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.exercises')),
            ],
            options={
                'db_table': 'SessionExercise',
            },
        ),
        migrations.CreateModel(
            name='SessionExercisesSets',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('set_number', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('session_exercise_id', models.ForeignKey(db_column='session_exercise_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.sessionexercise')),
            ],
            options={
                'db_table': 'SessionExercisesSets',
            },
        ),
        migrations.CreateModel(
            name='UserWeightHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('measured_at', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('Users_id', models.ForeignKey(db_column='Users_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.users')),
            ],
            options={
                'db_table': 'UserWeightHistory',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('is_active', models.IntegerField()),
                ('User_id', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.users')),
            ],
            options={
                'db_table': 'WorkoutPlan',
            },
        ),
        migrations.CreateModel(
            name='PlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=30)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('target_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.IntegerField()),
                ('exercise_id', models.ForeignKey(db_column='exercise_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.exercises')),
                ('plan_id', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.workoutplan')),
            ],
            options={
                'db_table': 'PlanExercise',
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('duration_min', models.IntegerField()),
                ('notes', models.CharField(max_length=45)),
                ('User_id', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.users')),
            ],
            options={
                'db_table': 'WorkoutSession',
            },
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='session_id',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.workoutsession'),
        ),
    ]
