# Generated by Django 5.2.10 on 2026-03-27 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('DifficultyLevel', models.CharField(blank=True, max_length=30, null=True)),
                ('category_id', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.categories')),
            ],
            options={
                'db_table': 'Exercises',
            },
        ),
        migrations.CreateModel(
            name='ExercisesGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exercises_exercise_id', models.ForeignKey(db_column='Exercises_exercise_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.exercises')),
                ('Goals_goal_id', models.ForeignKey(db_column='Goals_goal_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.goals')),
            ],
            options={
                'db_table': 'ExercisesGoals',
                'unique_together': {('Exercises_exercise_id', 'Goals_goal_id')},
            },
        ),
        migrations.AddField(
            model_name='exercises',
            name='goals',
            field=models.ManyToManyField(related_name='exercises', through='fitness.ExercisesGoals', to='fitness.goals'),
        ),
        migrations.CreateModel(
            name='PlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(blank=True, max_length=30, null=True)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('target_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.IntegerField()),
                ('exercise_id', models.ForeignKey(db_column='exercise_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.exercises')),
            ],
            options={
                'db_table': 'PlanExercise',
            },
        ),
        migrations.CreateModel(
            name='PlanExerciseSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('set_number', models.IntegerField()),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plan_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_sets', to='fitness.planexercise')),
            ],
            options={
                'db_table': 'PlanExerciseSet',
                'ordering': ['set_number'],
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('notes', models.CharField(max_length=255)),
                ('session_exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('exercise_id', models.ForeignKey(db_column='exercise_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.exercises')),
            ],
            options={
                'db_table': 'SessionExercise',
            },
        ),
        migrations.CreateModel(
            name='SessionExercisesSets',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('set_number', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('session_exercise_id', models.ForeignKey(db_column='session_exercise_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.sessionexercise')),
            ],
            options={
                'db_table': 'SessionExercisesSets',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('signup_date', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goal', models.ForeignKey(db_column='goal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.goals')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.AddField(
            model_name='exercises',
            name='User_id',
            field=models.ForeignKey(blank=True, db_column='User_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.users'),
        ),
        migrations.CreateModel(
            name='UserWeightHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('measured_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Users_id', models.ForeignKey(db_column='Users_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.users')),
            ],
            options={
                'db_table': 'UserWeightHistory',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('User_id', models.ForeignKey(blank=True, db_column='User_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.users')),
                ('exercise', models.ManyToManyField(related_name='plans', through='fitness.PlanExercise', to='fitness.exercises')),
                ('goal', models.ForeignKey(db_column='goal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.goals')),
            ],
            options={
                'db_table': 'WorkoutPlan',
            },
        ),
        migrations.AddField(
            model_name='planexercise',
            name='plan_id',
            field=models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.workoutplan'),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('duration_min', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('finished', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('User_id', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.users')),
                ('plan', models.ForeignKey(blank=True, db_column='WorkoutPlan_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='fitness.workoutplan')),
            ],
            options={
                'db_table': 'WorkoutSession',
            },
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='session_id',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.workoutsession'),
        ),
        migrations.CreateModel(
            name='ExerciseEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.equipment')),
                ('exercise_id', models.ForeignKey(db_column='exercise_id', on_delete=django.db.models.deletion.CASCADE, to='fitness.exercises')),
            ],
            options={
                'db_table': 'ExerciseEquipment',
                'unique_together': {('exercise_id', 'equipment_id')},
            },
        ),
    ]
