# Generated by Django 5.2.10 on 2026-03-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='signup_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
