# Generated by Django 5.2.10 on 2026-03-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='weight_current',
        ),
        migrations.AddField(
            model_name='users',
            name='goal',
            field=models.ForeignKey(db_column='goal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.goals'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='User_id',
            field=models.ForeignKey(blank=True, db_column='User_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.users'),
        ),
        migrations.AlterField(
            model_name='userweighthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='exerciseequipment',
            unique_together={('exercise_id', 'equipment_id')},
        ),
        migrations.AlterUniqueTogether(
            name='exercisesgoals',
            unique_together={('Exercises_exercise_id', 'Goals_goal_id')},
        ),
    ]
