# Generated by Django 5.2.10 on 2026-03-28 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_users_signup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planexercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='planexercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='planexercise',
            name='target_weight',
        ),
    ]
