# Generated by Django 5.2.10 on 2026-03-11 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_remove_users_weight_current_users_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='goals',
            field=models.ManyToManyField(related_name='exercises', through='fitness.ExercisesGoals', to='fitness.goals'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='exercise',
            field=models.ManyToManyField(related_name='plans', through='fitness.PlanExercise', to='fitness.exercises'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='User_id',
            field=models.ForeignKey(blank=True, db_column='User_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.users'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
