# Generated by Django 5.2.10 on 2026-03-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_remove_planexercise_reps_remove_planexercise_sets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='measure_type',
            field=models.CharField(choices=[('reps', 'Reps'), ('time', 'Time')], default='reps', max_length=10),
        ),
        migrations.AddField(
            model_name='planexerciseset',
            name='duration_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionexercisessets',
            name='duration_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
