# Generated by Django 5.2.10 on 2026-03-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_exercises_measure_type_planexerciseset_duration_sec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionexercisessets',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
