# Generated by Django 5.2.10 on 2026-03-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_exercises_goals_workoutplan_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planexercise',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
