# Generated by Django 5.2.10 on 2026-04-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_alter_sessionexercisessets_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='equipment',
            field=models.ManyToManyField(related_name='exercises', through='fitness.ExerciseEquipment', to='fitness.equipment'),
        ),
    ]
