# Generated by Django 5.2.10 on 2026-04-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_exercises_equipment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
