# Generated by Django 5.2.10 on 2026-03-13 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_planexercise_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planexercise',
            name='goal',
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='goal',
            field=models.ForeignKey(db_column='goal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.goals'),
        ),
    ]
