# Generated by Django 5.2.10 on 2026-04-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='equipment',
        ),
        migrations.AlterModelTable(
            name='exercises',
            table='exercises',
        ),
        migrations.AlterModelTable(
            name='exercisesgoals',
            table='exercisesGoals',
        ),
        migrations.AlterModelTable(
            name='goals',
            table='goals',
        ),
        migrations.AlterModelTable(
            name='planexercise',
            table='planExercise',
        ),
        migrations.AlterModelTable(
            name='planexerciseset',
            table='planExerciseSet',
        ),
        migrations.AlterModelTable(
            name='sessionexercise',
            table='sessionExercise',
        ),
        migrations.AlterModelTable(
            name='sessionexercisessets',
            table='sessionExercisesSets',
        ),
        migrations.AlterModelTable(
            name='userweighthistory',
            table='userWeightHistory',
        ),
        migrations.AlterModelTable(
            name='workoutplan',
            table='workoutPlan',
        ),
        migrations.AlterModelTable(
            name='workoutsession',
            table='workoutSession',
        ),
    ]
