# Generated by Django 5.2.10 on 2026-03-14 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_alter_workoutplan_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='DifficultyLevel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='category_id',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.categories'),
        ),
    ]
