# Generated by Django 5.2.10 on 2026-03-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_alter_exercises_difficultylevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
