# Generated by Django 5.2.10 on 2026-03-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_alter_workoutplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexercise',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionexercisessets',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
