# Generated by Django 5.2.10 on 2026-03-20 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_sessionexercise_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='plan',
            field=models.ForeignKey(blank=True, db_column='WorkoutPlan_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='fitness.workoutplan'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
